version: '3.7'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 6432:5432
    environment:
      - POSTGRES_DB=marketplace
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8082:8082"
    environment:
      - POSTGRES_NAME=marketplace
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    network_mode: host
    
  redis:
    image: 'redis:6.0.3'
    ports:
      - 6379:6379
    environment:
        - ALLOW_EMPTY_PASSWORD=yes
